
package com.edu.agh.sei;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ParkingPlaceSensor", targetNamespace = "http://impl.webservices.communication.agh.edu.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ParkingPlaceSensor {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "markParkingPlace", targetNamespace = "http://impl.webservices.communication.agh.edu.pl/", className = "com.edu.agh.sei.MarkParkingPlace")
    @ResponseWrapper(localName = "markParkingPlaceResponse", targetNamespace = "http://impl.webservices.communication.agh.edu.pl/", className = "com.edu.agh.sei.MarkParkingPlaceResponse")
    public void markParkingPlace(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ParkingPlaceState arg1);

    /**
     * 
     * @return
     *     returns java.util.List<com.edu.agh.sei.ParkingPlaceDetailsDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllParkingPlaces", targetNamespace = "http://impl.webservices.communication.agh.edu.pl/", className = "com.edu.agh.sei.GetAllParkingPlaces")
    @ResponseWrapper(localName = "getAllParkingPlacesResponse", targetNamespace = "http://impl.webservices.communication.agh.edu.pl/", className = "com.edu.agh.sei.GetAllParkingPlacesResponse")
    public List<ParkingPlaceDetailsDTO> getAllParkingPlaces();

}
